[project]
name = "BEMIO_examples"
version = "1.0.0"
description = "Various WEC studies with Capytaine for use in BEMIO and WEC-SIM"
requires-python = ">=3.8,<3.14"
dependencies = [
    "capytaine>=2.3.1",
    "xarray<2025.8",
    "vtk",
    "joblib"
]
